### ISSUE TITLE
Improve Docker installation procedure. (.env)

### ISSUE THREAD

**Issue by zarevskaya** [DumbWareio/DumbKan#1]
Hello,

For this part
https://github.com/abiteman/DumbKan#using-docker

git clone https://github.com/abiteman/dumbkan.git
cd dumbkan
docker build -t dumbkan .
cp .env.example .env
docker run -p 3000:3000 -v $(pwd)/data:/app/data --env-file .env dumbkan

Or withtout .env : 

```
#version: '3.9'
services:
    dumbkan:
        image: dumbkan
        environment:
            - DUMBKAN_PIN=1234
        volumes:
            - ./data:/app/data
        ports:
            - 3000:3000
```

Have a nice day!
